import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const lang = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={lang}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
